### ISSUE TITLE
On Mac, smart quotes are on by default and cause problems

### ISSUE THREAD

**Issue by GrantMeStrength** [jrincayc/ucblogo-code#162] opened 2023-03-08 20:36 UTC
On a Mac, editing a word definition will open the editor and any " characters entered will be converted to smart quotes which break code. This option can be turned off system-wide, but a better approach would be to disable this in the editor.

**Comment by dmalec** [comment] 2023-03-08 21:15
Agree on the better approach; this is also the root cause of issue #72. When I looked into that issue, my understanding was:
* This is something controlled within wxWidgets
* wxWidgets was not planning on addressing it within the 3.0.x family

That said, I'm game to look into something on the 3.0.x line if I overlooked an option there.

In terms of moving to the wxWidgets 3.2.x release (where it should be addressed), I had been planning on tackling that last year when 3.2 released; but, life happened :). My initial foray indicated that Linux and MacOS were straightforward; but, Windows was a bit trickier and I remember hitting a wall there.

(not to say this isn't worth tackling, I just figure it helps to have context about why it is the way it is currently)

**Comment by GrantMeStrength** [comment] 2023-03-22 23:55
"To disable smart quotation marks in wxWidgets, you can use the wxTextCtrl::SetAutoLayout method](https://docs.wxwidgets.org/3.0/classwx_button.html)" Not sure how accurate that is.

**Comment by dmalec** [comment] 2023-03-23 11:55
I wasn't able to find that phrase on the linked page or on the page for `wxTextCtrl` (https://docs.wxwidgets.org/3.0/classwx_text_ctrl.html). By any chance did you mean to post a different link?

I have mostly gotten the wxWidgets 3.2.x migration sorted, so, we should at least be able to use the approach introduced in 3.1.1 shortly.

**Closed** 2023-04-14 02:03 UTC
