### ISSUE TITLE
Cannot run logo scripts from command line

### ISSUE THREAD

**Issue by nixxon** [jrincayc/ucblogo-code#36] opened 2020-05-18 16:21 UTC
On Windows version 6.1, if I try to run a logo script from the command line, the script is not executed. Logo GUI is displayed instead (according to UCB Logo manual, this should not be the case), but nevertheless, the script is not running.

Steps to produce misbihavior: 

1. write this script and name it **example.logo**:
```print [This is my script] bye```
2. try to run the script from command line:
```"c:\Program Files (x86)\UCBLogo\ucblogo.exe" example.logo```

Result: nothing is printed on console, nor in the GUI window.

**Comment by jrincayc** [comment] 2020-05-19 00:08
Confirm (it also happens on the wx-windows linux version).

Thank you for reporting this.

**Comment by brianharvey** [comment] 2020-05-19 01:38
Fails on my Mac, too.

**Comment by zigggit** [comment] 2020-05-20 00:51
Not a bug, but a related request: It would be very nice to have a command line option to start Logo without the GUI, i.e. in pure text mode in the terminal window. If such an option already exists, I haven't noticed any reference to it in the documentation and a quick scan through the source didn't reveal it.

**Comment by jrincayc** [comment] 2020-10-29 01:48
Fixed with #59

**Closed by jrincayc** 2020-10-29 01:48 UTC
Labels: bug
